name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: FelipeGomez24
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/

      - name: Push to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          git rm -rf .
          cp -r dist/* .
          git add github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg
          git commit -m "Update snake animation"
          git push -f origin output
